name: CI Pipeline
on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Hello World!"
      - name: unit-test
        run: sleep 10
      - name: test
        run: echo "Hello World!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Hello World!"
