name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sleep 5

      - name: Compile source
        run: |
          echo "Compiling the application..."
          sleep 10

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          sleep 8
          echo "All unit tests passed!"

  automated-test:
    name: Automated Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run automated tests
        run: |
          echo "Running automated integration tests..."
          sleep 10
          echo "Automated tests passed successfully!"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: automated-test
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          sleep 7
          echo "Deployment complete"
